#include "LCD_2.h"




pins_t pins =
{
		.RS.GPIO_PORT = GPIO_PORT_A,
		.RS.GPIO_PIN = GPIO_PIN_0,
		.RS.GPIO_MODE = GPIO_OUTPUT_PP,
		.RS.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,


		.RW.GPIO_PORT = GPIO_PORT_A,
		.RW.GPIO_PIN = GPIO_PIN_1,
		.RW.GPIO_MODE = GPIO_OUTPUT_PP,
		.RW.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,


		.E.GPIO_PORT = GPIO_PORT_A,
		.E.GPIO_PIN = GPIO_PIN_2,
		.E.GPIO_MODE = GPIO_OUTPUT_PP,
		.E.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,


		.data[0] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_3,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},


		.data[1] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_4,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},


		.data[2] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_5,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},


		.data[3] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_6,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},


		.data[4] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_7,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},


		.data[5] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_8,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},


		.data[6] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_9,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		},



		.data[7] =
		{
		.GPIO_PORT = GPIO_PORT_A,
		.GPIO_PIN = GPIO_PIN_10,
		.GPIO_MODE = GPIO_OUTPUT_PP,
		.GPIO_SPEED = GPIO_SPEED_VERY_HIGH,
		}


};
